=== WiverMach/WiverMach.github.io/xml/menu.dtd
<!ELEMENT menu (meals, beverages)>
<!ELEMENT meals (meal+)>
<!ELEMENT meal (name, price, description, image)>
<!ELEMENT beverages (coffee, otherBeverages)>
<!ELEMENT coffee (size+, price+, description)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT otherBeverages (otherBeverage+)>
<!ELEMENT otherBeverage (name, price)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image (#PCDATA)>

=== WiverMach/WiverMach.github.io/xml/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu>
    <meals>
        <meal>
            <name>Beetroot and feta salad</name>
            <price>$15.00</price>
            <description>Suitable for vegetarians, made with fresh beetroot</description>
            <image>imagetest.jpg</image>
        </meal>
        <meal>
            <name>Sourdough Rye Sandwich</name>
            <price>$18.00</price>
            <description>Cheese and salad sandwich made with organic, sourdough rye bread</description>
            <image>imagetest.jpg</image>
        </meal>
        <meal>
            <name>Spinach Pie and Salad</name>
            <price>$20.00</price>
            <description>Tasty pie with salad</description>
            <image>imagetest.jpg</image>
        </meal>
        <meal>
            <name>Feta pancakes with salad</name>
            <price>$19.50</price>
            <description>Tasty pancake filled with feta and salad</description>
            <image>imagetest.jpg</image>
        </meal>
    </meals>

    <beverages>
        <coffee>
            <size>Small</size>
            <price>$3.50</price>
            <description>For coffee, please inform the staff of the coffee type.</description>
        </coffee>
        <coffee>
            <size>Regular</size>
            <price>$4.00</price>
            <description>For coffee, please inform the staff of the coffee type.</description>
        </coffee>
        <coffee>
            <size>Large</size>
            <price>$4.50</price>
            <description>For coffee, please inform the staff of the coffee type.</description>
        </coffee>

        <otherBeverages>
            <otherBeverage>
                <name>Soda</name>
                <price>$3.00</price>
            </otherBeverage>
            <otherBeverage>
                <name>Fresh juice</name>
                <price>$6.00</price>
            </otherBeverage>
            <otherBeverage>
                <name>Bottled water</name>
                <price>$2.00</price>
            </otherBeverage>
        </otherBeverages>
    </beverages>
</menu>
